name: Testing

on: [push]

jobs:
  Test:
    strategy:
      matrix:
        python-version:
        - "3.6"
        - "3.7"
        - "3.8"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: nanasess/setup-chromedriver@master
      - name: "Install Python dependencies (pip)"
        uses: "py-actions/py-dependency-install@v2"
        with:
          path: "requirements-5.2.x.txt"
          update-setuptools: "false"
          update-pip: "true"
          update-wheel: "true"
      - name: Cache eggs
        uses: actions/cache@v2
        with:
          path: |
            eggs
          key: eggs-${{ matrix.python-version }}
          restore-keys: eggs-
      - name: "Buildout"
        run: |
          buildout -c testing.cfg
      - name: "Test"
        run: |
            export DISPLAY=:99.0
            chromedriver --url-base=/wd/hub &
            sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
            sleep 3
            ROBOT_BROWSER=chrome bin/test --all

